name: "Benchmarks"

on:
    pull_request:
    push:
        branches:
            - 'master'

jobs:
    phpbench:
        name: "Run Benchmarks"

        runs-on: ubuntu-latest

        steps:

            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@2.7.0
              with:
                  tools: composer:v2

            - name: "Composer install"
              uses: "ramsey/composer-install@v1"

            - name: "Run benchmarks with PHPBench"
              run: vendor/bin/phpbench run --report=env --progress=travis

    foobar:
        name: "Run Benchmarks"

        runs-on: ubuntu-latest

        steps:

            - name: "Checkout code"
              uses: actions/checkout@v2.3.3

            - name: "Install PHP with extensions"
              uses: shivammathur/setup-php@2.7.0
              with:
                  tools: composer:v2

            - name: "Composer install"
              uses: "ramsey/composer-install@v1"

            - name: "Hello World"
              run: 'echo "Hello World"'

